server:
  #端口号
  port: 8001

#mybatis的配置
mybatis:
  #实体类别名
  type-aliases-package: cn.bdqn.pojo
  #sql映射文件
  mapper-locations: classpath:mapper/**/*.xml

#Spirng的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concatdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root